security:
    providers:
        token_authenticator:
            id: app.token_authenticator_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            anonymous: ~
            guard:
                authenticators:
                    - app.token_authenticator

    access_control:
        - { path: /, role: ROLE_USER }