parameters:

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator

    app.token_authenticator_user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@session"]